server:
  port: 93

spring:
  application:
    name: flight-service

  datasource:
    url: jdbc:postgresql://localhost:5432/db_flight
    username: your_username
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:90/eureka
