server:
  port: 92

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/db_user?useSSL=false&serverTimezone=UTC
    username: your_username
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:90/eureka
